spring:
  application:
    name: soa_service_a
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Anna2109
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  liquibase:
    enabled: false

  main:
    web-application-type: servlet

  gradle:
    user:
      home=C:/gradle_cache
